[package]
name = "wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
app = { path = "../app" }

[build-dependencies]
gear-wasm-builder.workspace = true
sails-client-gen.workspace = true
sails-idl-gen.workspace = true
app = { path = "../app" }
